<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!DOCTYPE html>
<html>
<head>
    <title>Example.com - Site Maintenance (503)</title>
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
	<link rel="stylesheet" type="text/css" href="css/styles.css">
</head>
<body>
<div id="clouds">
	<div class="cloud x1"></div>
	<div class="cloud x1_5"></div>
	<div class="cloud x2"></div>
	<div class="cloud x3"></div>
	<div class="cloud x4"></div>
	<div class="cloud x5"></div>
</div>
<div class='c'>
	<div class='_404'>Back in a few moments...</div>
	<div class='_1'>We're just making a few changes to improve your shopping experience</div>
	<hr>
	<div class='_2'>Here are some useful contact details if you need to get in touch:</div>
	<div class='_2'><span>Email:</span> customersupport@example.com</div>
	<div class='_2'><span>Telephone:</span> 01234 456 789</div>
</div>
<!-- Design Credit: SQFreaKz (https://codepen.io/sqfreakz/pen/GJRJOY) -->
</body>
</html>